-- MySQL Script generated by MySQL Workbench
-- Tue Jun 10 13:22:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trakt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trakt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trakt` DEFAULT CHARACTER SET utf8 ;
USE `trakt` ;

-- -----------------------------------------------------
-- Table `trakt`.`films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`films` ;

CREATE TABLE IF NOT EXISTS `trakt`.`films` (
  `id` INT NULL primary key AUTO_INCREMENT,
  `titel` VARCHAR(65) NOT NULL,
  `resleaseDatum` DATE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`series` ;

CREATE TABLE IF NOT EXISTS `trakt`.`series` (
  `id` INT NULL AUTO_INCREMENT,
  `titel` VARCHAR(65) NOT NULL,
  `aflevering` VARCHAR(150) NOT NULL,
  `releaseDatum` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`genres` ;

CREATE TABLE IF NOT EXISTS `trakt`.`genres` (
  `id` INT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`actuers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`actuers` ;

CREATE TABLE IF NOT EXISTS `trakt`.`actuers` (
  `id` INT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `geboorteDatum` DATE NULL,
  `leeftijd` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`genres_has_films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`genres_has_films` ;

CREATE TABLE IF NOT EXISTS `trakt`.`genres_has_films` (
  `genres_id` INT NOT NULL,
  `films_id` INT NOT NULL,
  PRIMARY KEY (`genres_id`, `films_id`),
  INDEX `fk_genres_has_films_films1_idx` (`films_id` ASC) VISIBLE,
  INDEX `fk_genres_has_films_genres1_idx` (`genres_id` ASC) VISIBLE,
  CONSTRAINT `fk_genres_has_films_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `trakt`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genres_has_films_films1`
    FOREIGN KEY (`films_id`)
    REFERENCES `trakt`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`series_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`series_has_genres` ;

CREATE TABLE IF NOT EXISTS `trakt`.`series_has_genres` (
  `series_id` INT NOT NULL,
  `genres_id` INT NOT NULL,
  PRIMARY KEY (`series_id`, `genres_id`),
  INDEX `fk_series_has_genres_genres1_idx` (`genres_id` ASC) VISIBLE,
  INDEX `fk_series_has_genres_series1_idx` (`series_id` ASC) VISIBLE,
  CONSTRAINT `fk_series_has_genres_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `trakt`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_series_has_genres_genres1`
    FOREIGN KEY (`genres_id`)
    REFERENCES `trakt`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`actuers_has_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`actuers_has_series` ;

CREATE TABLE IF NOT EXISTS `trakt`.`actuers_has_series` (
  `actuers_id` INT NOT NULL,
  `series_id` INT NOT NULL,
  PRIMARY KEY (`actuers_id`, `series_id`),
  INDEX `fk_actuers_has_series_series1_idx` (`series_id` ASC) VISIBLE,
  INDEX `fk_actuers_has_series_actuers1_idx` (`actuers_id` ASC) VISIBLE,
  CONSTRAINT `fk_actuers_has_series_actuers1`
    FOREIGN KEY (`actuers_id`)
    REFERENCES `trakt`.`actuers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actuers_has_series_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `trakt`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`actuers_has_films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`actuers_has_films` ;

CREATE TABLE IF NOT EXISTS `trakt`.`actuers_has_films` (
  `actuers_id` INT NOT NULL,
  `films_id` INT NOT NULL,
  PRIMARY KEY (`actuers_id`, `films_id`),
  INDEX `fk_actuers_has_films_films1_idx` (`films_id` ASC) VISIBLE,
  INDEX `fk_actuers_has_films_actuers1_idx` (`actuers_id` ASC) VISIBLE,
  CONSTRAINT `fk_actuers_has_films_actuers1`
    FOREIGN KEY (`actuers_id`)
    REFERENCES `trakt`.`actuers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actuers_has_films_films1`
    FOREIGN KEY (`films_id`)
    REFERENCES `trakt`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`gerbuikers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`gerbuikers` ;

CREATE TABLE IF NOT EXISTS `trakt`.`gerbuikers` (
  `id` INT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `familienaam` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`watchList_films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`watchList_films` ;

CREATE TABLE IF NOT EXISTS `trakt`.`watchList_films` (
  `id` INT NULL AUTO_INCREMENT,
  `Rating` INT NULL,
  `watchCount` INT NOT NULL,
  `gerbuikers_id` INT NOT NULL,
  `films_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gerbuikers_id`, `films_id`),
  INDEX `fk_watchList_films_gerbuikers1_idx` (`gerbuikers_id` ASC) VISIBLE,
  INDEX `fk_watchList_films_films1_idx` (`films_id` ASC) VISIBLE,
  CONSTRAINT `fk_watchList_films_gerbuikers1`
    FOREIGN KEY (`gerbuikers_id`)
    REFERENCES `trakt`.`gerbuikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watchList_films_films1`
    FOREIGN KEY (`films_id`)
    REFERENCES `trakt`.`films` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trakt`.`watchList_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trakt`.`watchList_series` ;

CREATE TABLE IF NOT EXISTS `trakt`.`watchList_series` (
  `id` INT NULL AUTO_INCREMENT,
  `rating` VARCHAR(45) NULL,
  `watchCount` INT NOT NULL,
  `gerbuikers_id` INT NOT NULL,
  `series_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gerbuikers_id`, `series_id`),
  INDEX `fk_watchList_series_gerbuikers1_idx` (`gerbuikers_id` ASC) VISIBLE,
  INDEX `fk_watchList_series_series1_idx` (`series_id` ASC) VISIBLE,
  CONSTRAINT `fk_watchList_series_gerbuikers1`
    FOREIGN KEY (`gerbuikers_id`)
    REFERENCES `trakt`.`gerbuikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watchList_series_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `trakt`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
